### ISSUE TITLE
Review Submission

### ISSUE THREAD

**Issue by not-xygen** [Ayiais/project1#1]
### Halo Ayu

Kode struktur kurang tepat, bis diperbaiki mengikuti contoh struktur dibawah yah:
```html
<main>
 <div id="banner">...</div>
 <div id="content-container">
  <div id="content">
   <section id="article">
    <article id="">...</article>
    ...
   </section>
   <section id="form">....</section>
    .....
  </div>
  <aside>....</div>
 </div>
</main>
```

Yang lain udah oke, bisa direvisi lalu upload ulang di repository ini juga, lalu komen dibawah jika sudah upload ulang ya. Terimakasih

**Comment by Ayiais** [comment]
Malam kak, saya sudah upload revisian struktur html yang kurang tepat. Terima kasih.

**Comment by not-xygen** [comment]
### Malam

Selamat submissionnya ku approve ya, mungkin asidenya tidak papa dibawah karena nanti akan dibaikin saat kamu belajar CSS

Goodluck CSSnya!
